# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z35OdvRIhi85NTgJeIu0oMpuzG3OcY3S
"""

"""
User API Fetcher - Google Colab Version
This script fetches user data from JSONPlaceholder API and displays it in a readable format.
It includes error handling and optional filtering for cities starting with 'S'.

To run in Google Colab:
1. Copy this entire code into a Colab cell
2. Click Run (or press Shift + Enter)
"""

import requests
import sys


def fetch_users():
    """
    Fetches user data from the JSONPlaceholder API.

    Returns:
        list: A list of user dictionaries if successful, None if failed
    """
    api_url = "https://jsonplaceholder.typicode.com/users"

    try:
        # Make GET request to the API
        print(" Fetching user data from API...")
        response = requests.get(api_url, timeout=10)

        # Check if the request was successful (status code 200)
        response.raise_for_status()

        # Parse JSON response
        users = response.json()

        # Check if the response contains data
        if not users:
            print("Warning: API returned an empty list of users.")
            return None

        print(f" Successfully fetched {len(users)} users.\n")
        return users

    except requests.exceptions.Timeout:
        print(" Error: Request timed out. Please check your internet connection.")
        return None
    except requests.exceptions.ConnectionError:
        print(" Error: Could not connect to the API. Please check your internet connection.")
        return None
    except requests.exceptions.HTTPError as e:
        print(f" Error: HTTP error occurred: {e}")
        return None
    except requests.exceptions.RequestException as e:
        print(f" Error: An error occurred while fetching data: {e}")
        return None
    except ValueError:
        print("Error: Could not parse JSON response from API.")
        return None


def display_users(users, filter_by_s=False):
    """
    Displays user information in a formatted manner.

    Args:
        users (list): List of user dictionaries
        filter_by_s (bool): If True, only display users whose city starts with 'S'
    """
    if not users:
        print("No users to display.")
        return

    displayed_count = 0

    # Loop through each user and display their information
    for index, user in enumerate(users, start=1):
        # Extract user details with safe defaults
        name = user.get('name', 'N/A')
        username = user.get('username', 'N/A')
        email = user.get('email', 'N/A')

        # Safely extract city from nested address object
        city = user.get('address', {}).get('city', 'N/A')

        # Apply filter if requested (Bonus feature)
        if filter_by_s and not city.startswith('S'):
            continue

        # Display user information
        displayed_count += 1
        print(f"User {index}:")
        print(f"  Name: {name}")
        print(f"  Username: {username}")
        print(f"  Email: {email}")
        print(f"  City: {city}")
        print(" ")

    # Show filter results
    if filter_by_s:
        print(f"\n Displayed {displayed_count} user(s) with cities starting with 'S'.")


def main():
    """
    Main function to run the script.
    """
    print("=" * 50)
    print(" User Data Fetcher - JSONPlaceholder API")
    print("=" * 50)
    print()

    # Fetch users from API
    users = fetch_users()

    # Exit if fetch failed
    if users is None:
        print("\n Script execution failed. Please try again.")
        return

    # Display all users
    print("\n" + "=" * 50)
    print(" ALL USERS")
    print("=" * 50)
    print()
    display_users(users)

    # Bonus: Display only users whose city starts with 'S'
    print("\n" + "=" * 50)
    print(" BONUS: USERS FROM CITIES STARTING WITH 'S'")
    print("=" * 50)
    print()
    display_users(users, filter_by_s=True)

    print("\n Script execution completed successfully!")


# Run the main function
if __name__ == "__main__":
    main()

